plugins:
  - git-tag
  - released
latest:
  noChangelog: true
shipit:
  noChangelog: true
labels:
  - name: BREAKING
    changelogTitle: '💥 Breaking Changes'
    description: 'Increment the major version when merged'
    releaseType: major
    color: '#C5000B'
  - name: feat
    changelogTitle: '🚀 Enhancements'
    description: 'Increment the minor version when merged'
    releaseType: minor
    color: '#F1A60E'
  - name: fix
    changelogTitle: '🐛 Patches'
    description: 'Increment the patch version when merged'
    releaseType: patch
    color: '#870048'
  - name: internal
    changelogTitle: '🏠 Internal'
    description: 'Changes only affect the internal API'
    releaseType: none
    color: '#696969'
  - name: documentation
    changelogTitle: '📝 Documentation'
    description: 'Changes only affect the documentation'
    releaseType: none
    color: '#cfd3d7'
  - name: tests
    changelogTitle: '🧪 Tests'
    description: 'Add or improve existing tests'
    releaseType: none
    color: '#ffd3cc'
  - name: dependencies
    changelogTitle: '📦 Dependency Updates'
    description: 'Update one or more dependencies version'
    releaseType: none
    color: '#8732bc'
  - name: skip-release
    description: 'Preserve the current version when merged'
    releaseType: skip
    color: '#bf5416'
