name: 'Coursier setup'
description: 'Install Coursier launcher and run cs setup'
inputs:
  jvm:
    description: 'JVM to install (leave empty to use default)'
    required: false
    default: ''
  apps:
    description: 'Applications to install'
    required: false
    default: 'sbtn'
outputs:
  cs-version:
    description: 'Version of the installed Coursier'
    value: ${{ steps.cs-setup.outputs.cs-version }}
runs:
  using: "composite"
  steps:
    - id: cs-setup
      shell: bash
      run: ${{ github.action_path }}/cs-setup.sh
