name: 'coursier-setup-action'
description: 'Use Coursier to install JVM and Scala apps'
author: 'Alexey Alekhin'
branding:
  icon: 'anchor'
  color: 'green'
inputs:
  jvm:
    description: 'JVM to install (leave empty to use default)'
    required: false
    default: ''
  jvm-index:
    description: 'Arbitrary URL containing the JVM index source (leave empty to use default)'
    required: false
    default: ''
  apps:
    description: 'Applications to install'
    required: false
    default: 'sbtn'
  version:
    description: 'Coursier version to install'
    required: false
    default: ''
  customRepositories:
    description: 'The pipe (|) seperated locations of non-standard repositories. See https://get-coursier.io/docs/other-repositories'
    required: false
    default: ''
  disableDefaultRepos:
    description: 'Whether to pass the --no-default flag to coursier'
    required: false
    default: 'false'
outputs:
  cs-version:
    description: 'Version of the installed Coursier'
runs:
  using: 'node20'
  main: 'dist/index.js'
