name: 'Coursier setup'
description: 'Install Coursier launcher and run cs setup'
inputs:
  jvm:
    description: 'JVM to install (leave empty to use default)'
    required: false
    default: ''
  apps:
    description: 'Applications to install'
    required: false
    default: 'sbtn'
outputs:
  cs-version:
    description: 'Version of the installed Coursier'
    value: ${{ steps.get-version.outputs.cs-version }}
runs:
  using: "composite"
  steps:
    - name: Install Coursier
      shell: bash
      run: |
        curl -fLo cs https://git.io/coursier-cli-linux &&
        chmod +x cs &&
        ./cs
    - name: Install JVM
      shell: bash
      run: '[ "${{ inputs.jvm }}" ] && eval "$(./cs java --env ${{ inputs.jvm }})"'
    - shell: bash
      run: echo $JAVA_HOME
    - name: Install Apps
      shell: bash
      run: '[ "${{ inputs.apps }}" ] && ./cs install ${{ inputs.apps }}'
    - shell: bash
      run: eval "$(./cs install --env)"
    - shell: bash
      run: echo $PATH
    - id: get-version
      shell: bash
      run: echo "::set-output name=cs-version::$(./cs --version)"
