on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: cs-setup
      uses: ./
      with:
        apps: sbt sbtn ammonite
    - run: echo cs-version=${{ steps.cs-setup.outputs.cs-version }}
    - run: echo $JAVA_HOME
    - run: echo $PATH
    - run: java -version
    - run: cs java -version
    - run: sbtn show sbtVersion
    - run: amm --help
