on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: cs-setup
      uses: ./
      with:
        # jvm: 11
        apps: sbt sbtn ammonite bloop scalafmt
    - uses: coursier/cache-action@v5
    - run: echo cs-version=${{ steps.cs-setup.outputs.cs-version }}
    - run: echo $JAVA_HOME
    - run: echo $PATH
    - run: java -version
    - run: cs java -version
    - run: |
        echo 'name := "foo"' > build.sbt
        sbtn show sbtVersion
    - run: amm --help
    - run: bloop about
    - run: scalafmt --help
