on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        jvm: ['8', '17']
    steps:
    - uses: actions/checkout@v4

    - name: Build
      shell: bash -l {0}
      run: |
        nvm use lts/gallium
        npm install
        npm run all

    # create an sbt file to enabling sbt caching
    - run: echo 'name := "foo"' > build.sbt
    - id: cs-setup
      uses: ./
      with:
        jvm: ${{ matrix.jvm }}
        apps: sbt sbtn ammonite bloop:1.4.11

    # - uses: coursier/cache-action@v5
    - run: echo cs-version=${{ steps.cs-setup.outputs.cs-version }}
    - run: echo $PATH

    # test Java
    - run: echo $JAVA_HOME
    - run: java -version
    - run: cs java -version

    # test installed apps
    - run: sbtn.bat show name </dev/null
      shell: bash
      if: runner.os == 'Windows'
    - run: sbtn show name
      if: runner.os != 'Windows'
    - run: amm --help
    - run: bloop about
